import os
import shutil
import glob

os.chdir('../')
if os.path.exists('RowBot Rally DEMO') is True:
    shutil.rmtree('RowBot Rally DEMO')
shutil.copytree('RowBot Rally/source', 'RowBot Rally DEMO')
os.chdir('RowBot Rally DEMO')

retain_dirs = [
    "/Users/rae/Developer/RowBot Rally DEMO/audio"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/music"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/story"
    "/Users/rae/Developer/RowBot Rally DEMO/fonts"
    "/Users/rae/Developer/RowBot Rally DEMO/images"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/stages"
    "/Users/rae/Developer/RowBot Rally DEMO/images/stages"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/card-highlighted"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/icon-highlighted"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/launchImages"
    "/Users/rae/Developer/RowBot Rally DEMO/images/ui"
    "/Users/rae/Developer/RowBot Rally DEMO/images/ui/fade"
]

retain_files = [
    "/Users/rae/Developer/RowBot Rally DEMO/boat.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/cutscene.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/en.strings"
    "/Users/rae/Developer/RowBot Rally DEMO/intro.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/main.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/notif.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/opening.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/options.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/pdxinfo"
    "/Users/rae/Developer/RowBot Rally DEMO/race.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/results.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/scenemanager.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/title.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/tutorial.lua"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/music/intro.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/music/opening.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/music/stage1.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/music/title.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/bonk.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/boost.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/clickoff.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/clickon.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/countdown.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/crash.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/finish.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/lose.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/menu.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/proceed.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/ref.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/row.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/rowboton.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/sea.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/start.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/ui.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/whoosh.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/sfx/win.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/story/scene1_music.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/story/scene1_sfx.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/story/scene2_music.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/audio/story/scene2_sfx.wav"
    "/Users/rae/Developer/RowBot Rally DEMO/fonts/double_time.fnt"
    "/Users/rae/Developer/RowBot Rally DEMO/fonts/kapel_doubleup.fnt"
    "/Users/rae/Developer/RowBot Rally DEMO/fonts/kapel.fnt"
    "/Users/rae/Developer/RowBot Rally DEMO/fonts/pedallica.fnt"
    "/Users/rae/Developer/RowBot Rally DEMO/fonts/times_new_rally.fnt"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/stages/stagetut.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/stages/stagectut.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/stages/stage1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/stages/stagec1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/stages/water.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/stages/water_bg.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/boost-table-1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/boost-table-2.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/boost-table-3.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/boost-table-4.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/boost-table-5.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/boost-table-6.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/countdown.gif"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/meter.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/net.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/results_lose.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/results_win.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/timer_1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/timer_2.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/timer_3.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/race/timer.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/stages/preview1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/stages/gimmick_container.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/stages/gimmick_icons-table-65-48.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_intro-table-1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_intro-table-2.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_intro-table-3.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_intro-table-4.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_intro-table-5.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_intro-table-6.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_intro-table-7.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_intro-table-8.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_outro-table-1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_outro-table-2.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_outro-table-3.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_outro-table-4.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_outro-table-5.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_outro-table-6.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_outro-table-7.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border_outro-table-8.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border-table-1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border-table-2.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border-table-3.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/border-table-4.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/opening-table-1.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/opening-table-2.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/opening-table-3.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/scene1.pdv"
    "/Users/rae/Developer/RowBot Rally DEMO/images/story/scene2.pdv"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/card.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/card-pressed.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/icon.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/icon-pressed.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/launchImage.png"
    "/Users/rae/Developer/RowBot Rally DEMO/images/system/wrapping-pattern.png"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
    "/Users/rae/Developer/RowBot Rally DEMO/"
]

with open(os.getcwd() + '/pdxinfo', 'r') as f:
    fd = f.read()
fd = fd.replace('RowBot Rally', 'RowBot Rally DEMO')
fd = fd.replace('wtf.rae.rowbotrally', 'wtf.rae.rowbotrallydemo')
with open(os.getcwd() + '/pdxinfo', 'w') as f:
    f.write(fd)